### ISSUE TITLE
Toplist wins & win_ratio updated even only one participant

### ISSUE THREAD

**Issue by cyberkeiler** [TrollskogenMC/racing#17]
I love your new toplist feature! Especially the

>  /rc toplist fastest

 one. Love you now show one decimal digit of the elapsed time as well!

Only one minor critic point:
The wins and win_ratio Toplist is more ore less useless for our use if races with only one participant is counted as well.

I'm not sure if there is a minimum participant config planned yet, which can avoid this behaviour or if its better to just don't add single-participant races to the toplist categories of wins and win_ratio.

Thanks a lot!

This is our manual workaround at the moment:
Create 2 Races for the exact same Track: 
- 1 single lap race to track the fastest Lap_record (+ used as Qualifying) for single participant usage
- 3 lap main Event race for the Win/Lose Statistics only be used by more than 1 participant

**Comment by hornta** [comment]
I agree with your points. What do you think about an option `minimimRequiredPlayerToStart` per race which defaults to 1?

**Comment by cyberkeiler** [comment]
Great. Would be one more fantastic config option. 


But if you could additionally just make the increment of wins and win ration conditional for participants >1 that would just make more sense.

But I see your problem. At the moment you just track down the players runs and wins. 
So you would need an additional variable (like losts, or multiplayer_runs) in the races results to keep track of the win_ratio, when runs continues to count all races even with 1 participant. 
(Hope you get my point ;) )

**Comment by hornta** [comment]
I know there are some cases where a leaderboard type for example "wins" or "runs" doesn't really add any value for certain races, but I'm not so sure I want to add results conditonally since races can be made to host either 1 or 100 players. What do you think of having a way of disabling a leaderboard type for certain races?

**Comment by hornta** [comment]
@cyberkeiler Fixed in 2.4.0
