### ISSUE TITLE
Prevent joining races from certain worlds

### ISSUE THREAD

**Issue by hornta** [TrollskogenMC/racing#31]

**Comment by TobyMinceraft** [comment]
I do know of a workaround for this issue using the Skript plugin (primarily, the fork by "bensku"), but this would make it easier, definitely. It would be something like this:
`on command "/racing ":
    if player's world is "CaseSensitiveNameOfWorld" or "AnotherWorld":
        cancel event
        send "&cThat command is disabled in this world"
        stop`

Of course, you would have to do this with each racing alias (i.e. "/racing ", "/rc ", "/racing:racing ", and "/racing:rc " - and yes, the space after the command is **required**)

**Comment by hornta** [comment]
@TobyMinceraft Added in 2.3.0
