### ISSUE TITLE
Suggestion: Jump pads

### ISSUE THREAD

**Issue by CWKevo** [TrollskogenMC/racing#34]
Basically jump pads for boats/other entities & players to make them compatible over different types of races, so I don't have to use soul sand underwater and/or slime blocks.

**Comment by hornta** [comment]
I have thought about this. I know there are several good jump pad plugins like for example https://www.spigotmc.org/resources/custom-jumppads-1-8-1-14.44876/ but I'm not sure it supports boats or players riding horses/pigs. Do you wanna talk with that plugin developer and see if it supports boats?
Although I liked how your race featured soulsand elevators for vertical movement, kinda smart.

**Comment by hornta** [comment]
This shouldn't be a part of Racing since there are good jump pad plugins out there.
