### ISSUE TITLE
Make points radius configurable in config

### ISSUE THREAD

**Issue by philipkoivunen** [TrollskogenMC/racing#4]
Preferably by race-type

**Comment by cyberkeiler** [comment]
I totally see a point with radius per Checkpoint. Love the possibility to already change it via the .yml! Especially in Flight Races there may be narrow and wide checkpoint areas in the same race

**Comment by nordlead2005** [comment]
I think there should be a mode where you click both sides of the checkpoint to create the radius. For ice boat racing, the path isn't always the same width, and I don't want users to be able to sneak around the checkpoint on accident.

**Comment by Crux-Ansata** [comment]
I have adapted this in the config, as my race track was larger than the checkpoint and players would miss it. Now it works great. You can specify each checkpoint seperately and chose different radius, or keep them all the same!

**Comment by hornta** [comment]
Radius of checkpoints can be changed in the race configuration file.
