### ISSUE TITLE
Using the same command with residence"/rc"

### ISSUE THREAD

**Issue by haohaostudio** [TrollskogenMC/racing#55]
When click on the message which printed out, it shows /
![image](https://user-images.githubusercontent.com/22652631/80792584-57710980-8bc7-11ea-9336-8e349ed8db0e.png)
Can you make the click events execute /racing instead of /rc?

**Comment by hornta** [comment]
Do you mean the /rc skipwait, /rc join and /rc stop command you get in the chat when you start the race?

**Comment by hornta** [comment]
rc is just an alias for racing

**Comment by haohaostudio** [comment]
but when player click on the message toasted on the screen, it shows the message by the res plugin.

**Comment by haohaostudio** [comment]
> Do you mean the /rc skipwait, /rc join and /rc stop command you get in the chat when you start the race?

yes

**Comment by hornta** [comment]
Fixed in 2.0.0
