### ISSUE TITLE
Dropbox link for version 3.0

### ISSUE THREAD

**Issue by enderslayer2006** [TrollskogenMC/racing#67]
Racing version 3.0. Dropbox file not download able please fix this i really want to try the plugin on my 1.16.1 server thx.

**Comment by hornta** [comment]
It's available in Dropbox:
https://www.dropbox.com/sh/hbejuoc6fzh51vl/AACg-aqt7Wu8BeW5HiiJUr_ra?dl=0
![image](https://user-images.githubusercontent.com/4553604/91692734-28b17280-eb6a-11ea-9db8-77e4b811a062.png)
