### ISSUE TITLE
Make checkpoints bigger?

### ISSUE THREAD

**Issue by Anston06** [TrollskogenMC/racing#69]
Is it possible you could add the abilty to make checkpooints bigger?

**Comment by hornta** [comment]
It's possible right now by editing the checkpoint radius in the race file.

**Comment by Anston06** [comment]
Ah, Thanks. I don't know how I missed that!

**Comment by hornta** [comment]
After editing the file you can do /rc reload. You shouldn't need to restart the server inbetween.
